### PR TITLE
configurable screen size

### PR DESCRIPTION
**Pull request by heeen**
* query Qt.application.screens for screen size
* use env variable on desktop to override size

### CODE REVIEW

**Comment by heeen** [comment]
disclaimer: I haven't checked if `Qt.application.screens` actually works correctly on etnaviv

**Review by EugenWiens — APPROVED** [review]
for me it looks fine, we have definitely to test ` Qt.application.screens[0].width` on the target

**Comment by ChHapp** [comment]
@heeen I suppose `Qt.application.primaryScreen` might be a better approach as Qt.application.screens[0]. I have not give it a try yet, what do you think about it?

**Comment by heeen** [comment]
primaryScreen is undefined when testing on my desktop with 2 screens, which is odd.

**Review by ChHapp — APPROVED** [review]

**Pull request merged**
