### PR TITLE
Add configuration option for setting custom boot screen QML file

### LINKED ISSUE #1: Support alternative UI imlementations for TaskSwitcher, Notifications, Bootscreen

### PR DESCRIPTION
**Pull request by heeen**
* configuration option for bootscreen/global overlay implementation
* example alternative bootscreen

fixes #1

### CODE REVIEW

**Review by EugenWiens — APPROVED** [review]
looks fine for me

**Review by ChHapp — APPROVED** [review]
works like a charm :+1:

**Review by ChHapp — APPROVED** [review]
works like a charm :+1:

**Review by ChHapp — APPROVED** [review]
works like a charm :+1:

**Review by ChHapp — APPROVED** [review]
works like a charm :+1:

**Review by ChHapp — APPROVED** [review]
works like a charm :+1:

**Review by ChHapp — APPROVED** [review]
works like a charm :+1:

**Review by ChHapp — APPROVED** [review]
works like a charm :+1:

**Pull request merged**
