### PR TITLE
Dbus taskswitch

### LINKED ISSUE #2: Implement DBus Method to select active view on taskswitcher interface

### PR DESCRIPTION
**Pull request by heeen**
create dbus interface for switching current view to a different one. 

* surfaces/views are identiefied by uuid
* list of views includes uuid, label and process id for easy identification of the view

Fixes #2

### CODE REVIEW

**Comment by ChHapp** [comment]
@heeen does this PR relsove one of the issues (https://github.com/JUMO-GmbH-Co-KG/embedded-compositor/issues) ?

**Comment by heeen** [comment]
This implements #2

**Comment by ChHapp** [comment]
@heeen Could you rebase this branch please? I have already merged the first PR :tada:, there should not be so much changed files anymore.

**Comment by EugenWiens** [comment]
> @heeen Could you rebase this branch please? I have already merged the first PR tada, there should not be so much changed files anymore.

@heeen The changes are not only for the feature `dbus taskswitch` please rebase first to make the review easier. Thx.

**Comment by EugenWiens** [comment]
now it looks good for me, @heeen cold you please adapt the documentation for the dbus API to finalize the PR.

**Comment by ChHapp** [comment]
I am also happy with it :+1: 

I have tested it via `dbus-send` as far I can say it works as expected. 
One thing I have noticed is that if you have open the taskswitcher, the shown text (uuid) of each available view seems not to fit into the minify widget overview. I guess it is only for debug reason visible ...

**Review by ChHapp — APPROVED** [review]

**Pull request merged**
